### ISSUE TITLE
check dependencies

### ISSUE THREAD

**Issue by beanumber** [baumer-lab/sds192#4]
@ambertin can we get this to install without the external dependencies?

**Comment by ambertin** [comment]
By this, do you mean can we get Fertile to install properly without also needing to install the packages it is dependent on? As in moving some of them to suggests instead of depends?

**Comment by ambertin** [comment]
Just made a change in 178f0cf.

It looks like the only true dependencies are `digest` and `remotes` so I left those as the only packages in "Imports". `fertile` and `wordcountaddin` are now both under "Suggests" since loading `sds192` should install them for us. I think this will fix the problem since now the only dependencies are packages available on CRAN.

Also I'm not sure what the `imports.R` file is supposed to do but I thought it might have something to do with the dependency issue so I commented it out for now. If it's doing something important and you don't think it will cause a problem with installing `sds192` then let me know and I can un-comment it!

**Comment by beanumber** [comment]
In the markdown template we call `sds192::text_stats()`, which is just `wordcountaddin::text_stats()`.

**Comment by ambertin** [comment]
I was working on trying to do the same strategy we did with Hadley's requirements in fertile, but it looks like you got there first! Your new updates seem to work on my end. I can now install the package from this repo without already having fertile and wordcountaddin installed! To confirm, I will go ahead and see if I can get someone else to try and see if their results match.

**Comment by beanumber** [comment]
What happens when you run `devtools::check()`? Mine just hangs...

**Comment by beanumber** [comment]
Because it is installing like a million packages. This approach makes me nervous.

**Comment by ambertin** [comment]
Runs just fine for me but I get this warning:

![Screen Shot 2020-08-04 at 3 44 08 PM](https://user-images.githubusercontent.com/33032410/89343092-62758300-d669-11ea-9af4-576c3f378dd7.png)

**Comment by ambertin** [comment]
Also, correct me if I am wrong on this, but although this method installs a lot of packages, I don't think it is any different than having students install `wordcountaddin` themselves before installing `sds192`, since doing that would also install all of the packages that `wordcountaddin` is dependent on. This way, however, we have the significant benefit of reducing student error. Even though the README document we had before had clear instructions on the order in which you had to install these packages before proceeding, students were consistently getting it wrong as if they had just completely skipped the instructions. Doing it this way removes the headache of having to deal with all of those errors/questions from students and makes installation much smoother. That feels worth it to me, but I might be missing something since I am much less familiar with dependencies and how they work than you are.

**Comment by beanumber** [comment]
Mine hangs on:

```
* checking loading without being on the library search path
```

about which Hadley says: http://r-pkgs.had.co.nz/check.html

> Checking loading without being on the library search path. Calls library(x, lib.loc = ...). > Failure here indicates that you are making a false assumption in .onLoad() or .onAttach().

I worry that we are trying to be too clever and are obviating the checks that were put in place to prevent people from doing exactly what we are trying to do. And even though it might work for us, it will fail in all kinds of unpredictable ways once we unleash it on users.

**Comment by beanumber** [comment]
Also

* having them learn that they have to install dependencies for some packages is not a bad outcome
* I was able to troubleshoot everyone's `sds192` installation failures by installing the dependencies.

**Comment by ambertin** [comment]
That makes a lot of sense! Perhaps better to add another step than to trick the system. I’ll go ahead and revert back to the old set-up shortly.

**Comment by beanumber** [comment]
I got it.
